export const workbookAreas = [
  'COMPONENTES MANIOBRAS (STOCK)',
  'CONTROLLER CMC',
  'COP NUEVAS DECORACIONES',
  'CTROL.CMC ESPECIALES +ALU.HUECO CENE',
  'KIT EXPEDIBLE',
  'KIT EXPEDIBLE MOD FR',
  'KIT PICKING',
];

export const workbookCategories = [
  'DOCUMENT/METODO TRABAJO',
  'MANO DE OBRA',
  'MAQUINA/MANTENIMIENTO',
  'MATERIAL',
  'OTROS',
  'SEGURIDAD',
];

export const workbookIssueTypes = [
  'AVERIA/PARO MAQ',
  'CAMBIO IMPREVISTO DE PLANIFICACION',
  'DEFECTUOSO/DAÑADO',
  'DOCUMENTACION ERRÓNEA/INCORRECTA',
  'DOCUMENTACIÓN FALTANTE',
  'ERRONEO',
  'ERROR MONTAJE',
  'FALLO INFORMÁTICO',
  'FALTA',
  'FALTA HERRAMIENTA/ÚTIL',
  'INCIDENCIA DATAMATRIX',
  'MANTENIMIENTO,REPARACION',
  'NEAR MISS/CASI ACCIDENTE',
  'NO DEFINIDO',
  'OTROS',
  'PROCESO NO DEFINIDO Ó INCORRECTO',
  'ROTURA HERRAMIENTA/ÚTIL',
  'SIN ETIQUETA/MAL IDENTIFICADO',
  'SITUACIÓN INSEGURA',
  'TIEMPO OPERACIÓN INSUFICIENTE',
];